server:
  port: 7001
security:
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: name     # 用户名
    password: passwd  # 密码
spring:
  application:
    name: testcloud-eureka
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://name:passwd@116.62.23.39:7002/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7001 # 定义Eureka实例所在的主机名称