server:
  port: 9501

ribbon:
  eureka:
   enabled: false
   
testcloud-provider-dept:
  ribbon:
    listOfServers: http://localhost:8001,http://localhost:8002
    
zuul:
  ignored-services:
    "*"
  routes:
    testcloud-provider-company:
      path: /company-proxy/** 
    testcloud-provider-dept: 
      path: /dept-proxy/**
      service-id: testcloud-provider-dept
    testcloud-provider-upload:
      path: /upload-proxy/**
  sensitive-headers:   #过滤的header列表"Cookie", "Set-Cookie", "Authorization"
#  add-host-header: true #处理HTTP请求头信息中的Host

security:
  basic:
    enabled: false
  user:
    name: zuul
    password: 123456
    
info:
  app.name: test-zuul
  company.name: www.test007.cc
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

spring:
  application:
    name: testcloud-zuul-gateway
