server:
  port: 9501

ribbon:
  eureka:
   enabled: false
   
testcloud-provider-dept:
  ribbon:
    listOfServers: http://localhost:8001,http://localhost:8002
    
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000
  ignored-services:
    "*"
  routes:
    testcloud-provider-company:
      path: /company-proxy/** 
    testcloud-provider-dept: 
      path: /dept-proxy/**
      service-id: testcloud-provider-dept
    testcloud-provider-upload:
      path: /upload-proxy/**
  ratelimit:
      enabled: true #default false
      behind-proxy: true #default false
      policies:
        product:
          limit: 10
          refresh-interval: 120 #60 default value (in seconds)
          type: #optional
            - user
            - origin
            - url
  sensitive-headers:   #过滤的header列表"Cookie", "Set-Cookie", "Authorization"
#  add-host-header: true #处理HTTP请求头信息中的Host

security:
  basic:
    enabled: false
  user:
    name: zuul
    password: 123456
    
info:
  app.name: test-zuul
  company.name: www.test007.cc
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

spring:
  application:
    name: testcloud-zuul-gateway
  redis:
    timeout: 10
    database: 0
    host: 116.62.23.39
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0