server:
  port: 9501

ribbon:
  eureka:
   enabled: false
   
testcloud-provider-dept:
  ribbon:
    listOfServers: http://localhost:8001,http://localhost:8002
    
zuul:
  ignored-services:
    "*"
  routes: 
    testcloud-provider-company:
      path: /company-proxy/** 
    testcloud-provider-dept: 
      path: /dept-proxy/**
      service-id: testcloud-provider-dept
    testcloud-provider-upload: 
      path: /upload-proxy/**

security:
  basic:
    enabled: true
  user:
    name: name
    password: passwd
    
info:
  app.name: test-zuul
  company.name: www.test007.cc
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

spring:
  application:
    name: testcloud-zuul-gateway
